Fixed Cipher Suite RMCP+ Privileges
Related link:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-host-ipmid/+/50610

IPMI is communicating even when RMCP+ Messaging Cipher Suite Privilege Levels is set to operator, user, call back and unspecified.

Error Test Cases:
-----------------

Unspecified:
------------
root@dgx:~# ipmitool raw 0x0c 0x01 0x01 0x18 0x0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00

root@dgx:~# ipmitool raw 0x0c 0x02 0x01 0x18 0 0
 11 00 00 00 00 00 00 00 00 00
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 raw 6 1
 00 65 02 09 02 8d 47 16 00 00 00 15 00 00 00
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L user raw 6 1
 00 65 02 09 02 8d 47 16 00 00 00 15 00 00 00
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L operator raw 6 1
 00 65 02 09 02 8d 47 16 00 00 00 15 00 00 00
root@dgx:~#

callback:
--------

root@dgx:~# ipmitool raw 0x0c 0x01 0x01 0x18 0x0 0x11 0x11 0x11 0x11 0x11 0x11 0x11 0x11

root@dgx:~# ipmitool raw 0x0c 0x02 0x01 0x18 0 0
 11 00 11 11 11 11 11 11 11 11
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 raw 6 1
 00 65 02 09 02 8d 47 16 00 00 00 15 00 00 00
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L user raw 6 1
 00 65 02 09 02 8d 47 16 00 00 00 15 00 00 00
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L operator raw 6 1
 00 65 02 09 02 8d 47 16 00 00 00 15 00 00 00

user:
-----

root@dgx:~# ipmitool raw 0x0c 0x01 0x01 0x18 0x0 0x22 0x22 0x22 0x22 0x22 0x22 0x22 0x22

root@dgx:~# ipmitool raw 0x0c 0x02 0x01 0x18 0 0
 11 00 22 22 22 22 22 22 22 22
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 raw 6 1
 00 65 02 09 02 8d 47 16 00 00 00 15 00 00 00
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L user raw 6 1
 00 65 02 09 02 8d 47 16 00 00 00 15 00 00 00
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L operator raw 6 1
 00 65 02 09 02 8d 47 16 00 00 00 15 00 00 00

OEM:
----

root@dgx:~# ipmitool raw 0x0c 0x01 0x01 0x18 0x0 0x55 0x55 0x55 0x55 0x55 0x55 0x55 0x55

root@dgx:~# ipmitool raw 0x0c 0x02 0x01 0x18 0 0
 11 00 55 55 55 55 55 55 55 55
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 raw 6 1
 00 65 02 09 02 8d 47 16 00 00 00 15 00 00 00
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L user raw 6 1
 00 65 02 09 02 8d 47 16 00 00 00 15 00 00 00
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L operator raw 6 1
 00 65 02 09 02 8d 47 16 00 00 00 15 00 00 00

Test cases After fix:
---------------------

root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 raw 0x0c 0x02 0x01 0x18 0 0
 11 00 44 44 44 44 44 44 44 44
root@dgx:~# ipmitool lan print
Set in Progress         : Set Complete
Auth Type Support       :
Auth Type Enable
                        : Callback :
                        : User     :
                        : Operator :
                        : Admin    :
                        : OEM      :
IP Address Source       : DHCP Address
IP Address              : 10.19.102.17
Subnet Mask             : 255.0.0.0
MAC Address             : 7a:78:0c:9c:0d:8f
Default Gateway IP      : 0.0.0.0
Default Gateway MAC     : 00:00:00:00:00:00
802.1q VLAN ID          : Disabled
RMCP+ Cipher Suites     : 17
Cipher Suite Priv Max   : aaaaaaaaaaaaaaa
                        :     X=Cipher Suite Unused
                        :     c=CALLBACK
                        :     u=USER
                        :     o=OPERATOR
                        :     a=ADMIN
                        :     O=OEM
Bad Password Threshold  : Not Available
root@dgx:~#

root@dgx:~# ipmitool raw 0x0c 0x02 0x01 0x18 0 0
 11 00 44 44 44 44 44 44 44 44
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 raw 6 1
 00 65 02 09 02 8d 47 16 00 00 00 15 00 00 00
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L user raw 6 1
 00 65 02 09 02 8d 47 16 00 00 00 15 00 00 00
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L operator raw 6 1
 00 65 02 09 02 8d 47 16 00 00 00 15 00 00 00

Unspecified:
-----------

root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 raw 0x0c 0x01 0x01 0x18 0x0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00

root@dgx:~# ipmitool raw 0x0c 0x02 0x01 0x18 0 0
 11 00 00 00 00 00 00 00 00 00
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 raw 6 1
Error: Unable to establish IPMI v2 / RMCP+ session
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L user raw 6 1
Error: Unable to establish IPMI v2 / RMCP+ session
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L operator raw 6 1
Error: Unable to establish IPMI v2 / RMCP+ session

Callback :
---------
root@dgx:~# ipmitool raw 0x0c 0x01 0x01 0x18 0x0 0x11 0x11 0x11 0x11 0x11 0x11 0x11 0x11

root@dgx:~# ipmitool raw 0x0c 0x02 0x01 0x18 0 0
 11 00 11 11 11 11 11 11 11 11
root@dgx:~#
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 raw 6 1
Error: Unable to establish IPMI v2 / RMCP+ session
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L user raw 6 1
Error: Unable to establish IPMI v2 / RMCP+ session
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L operator raw 6 1
Error: Unable to establish IPMI v2 / RMCP+ session

user:
----
ipmitool raw 0x0c 0x01 0x01 0x18 0x0 0x22 0x22 0x22 0x22 0x22 0x22 0x22 0x22

ipmitool raw 0x0c 0x02 0x01 0x18 0 0
 11 00 22 22 22 22 22 22 22 22
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 raw 6 1
Error: Unable to establish IPMI v2 / RMCP+ session
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L user raw 6 1
 00 65 02 09 02 8d 47 16 00 00 00 15 00 00 00
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L operator raw 6 1
Error: Unable to establish IPMI v2 / RMCP+ session

OEM:
---------

root@dgx:~# ipmitool raw 0x0c 0x01 0x01 0x18 0x0 0x55 0x55 0x55 0x55 0x55 0x55 0x55 0x55

root@dgx:~# ipmitool raw 0x0c 0x02 0x01 0x18 0 0
 11 00 55 55 55 55 55 55 55 55
root@dgx:~#
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 raw 6 1
Error: Unable to establish IPMI v2 / RMCP+ session
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L user raw 6 1
Error: Unable to establish IPMI v2 / RMCP+ session
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L operator raw 6 1
Error: Unable to establish IPMI v2 / RMCP+ session
root@dgx:~# ipmitool -H 10.19.102.17 -I lanplus -U root -P Nvidia_123 -C 17 -L callback raw 6 1
Error: Unable to establish IPMI v2 / RMCP+ session

Signed-off-by: shamim ali <shamima@ami.com>
Change-Id: I521521ab415ca47ca865e2fc26ddf333f087c352