gcc14: fix C++ One Definition Rule
The following error occurs when building with gcc14:
```
| message.hpp:117:8: error: type 'struct Message' violates the C++ One Definition Rule [-Werror=odr]
| message.hpp:117:8: note: a different type is defined in another translation unit
| message.hpp:261:26: note: the first difference of corresponding definitions is field 'payload'
| message.hpp:250:13: note: a field with different name is defined in another translation unit
```

This is because some files that include this header have included
config.h, and some have not. config.h defines the RMCP_PING compile
flag.

Tested:
- Confirmed this now compiles with gcc14

Change-Id: I7f3705bdc21cc05cc7fedb591f198cbf9dc9365d
Signed-off-by: Andrew Geissler <geissonator@yahoo.com>