net_ipmi: move closeOtherNetInstanceSession to use managed sessions
`closeOtherNetInstanceSession` is running into issue with ELOOP because
it is still calling service managed by netipmid
(`xyz.openbmc_project.Ipmi.Channel.usb0`).

```
 sd_bus_call: System.Error.ELOOP: Too many levels of symbolic links
```

Tested:
Ran the following multiple times
```
for ((i=0; i<10; i++)); do
  ./ipmitool -I lanplus -H fe80::a0d5:9dff:fe6c:6e6a%sleipnir0 \
    -U root -P 0penBmc fru &
done
...

Before the change it will failed to close the session and run out of
available sessions.

For example,
```
Close Session command failed: Unspecified error
```

```
Error: Unable to establish IPMI v2 / RMCP+ session
```

After this change, no more errors and all close/create sessions are
successful.

Change-Id: Ibaf26fb2e554fa530542587b380891ee6f60ec0d
Signed-off-by: Willy Tu <wltu@google.com>