net-ipmid: sol: Fixed setSolConfParams return invalid
Problem:
Command setSolConfParams return invalid command.
ipmitool  -I lanplus -H 10.0.2.15 -U root -P 0penBmc sol set enabled true
Error setting SOL parameter 'set-in-progress' to 'set-in-progress': Invalid command
Error: set of parameter "enabled" failed

Root Cause:
Lack command handler.

Solution:
Add setSolConfParms command handler.

Tested:
1. Show Sol Info:
ipmitool -I lanplus -H 10.0.2.15 -U root -P 0penBmc sol info
Info: SOL parameter 'Nonvolatile Bitrate (5)' not supported
Info: SOL parameter 'Volatile Bitrate (6)' not supported
Set in progress                 : set-complete
Enabled                         : true
Force Encryption                : false
Force Authentication            : false
Privilege Level                 : ADMINISTRATOR
Character Accumulate Level (ms) : 500
Character Send Threshold        : 1
Retry Count                     : 7
Retry Interval (ms)             : 1000
Volatile Bit Rate (kbps)        : IPMI-Over-Serial-Setting
Non-Volatile Bit Rate (kbps)    : IPMI-Over-Serial-Setting
Payload Channel                 : 1 (0x01)
Payload Port                    : 623

2. Set Sol Conf:
ipmitool -I lanplus -H 10.0.2.15 -U root -P 0penBmc sol set enabled false
ipmitool -I lanplus -H 10.0.2.15 -U root -P 0penBmc sol set force-encryption true
ipmitool -I lanplus -H 10.0.2.15 -U root -P 0penBmc sol set force-authentication true
ipmitool -I lanplus -H 10.0.2.15 -U root -P 0penBmc sol set privilege-level user
ipmitool -I lanplus -H 10.0.2.15 -U root -P 0penBmc sol set character-accumulate-level 200
ipmitool -I lanplus -H 10.0.2.15 -U root -P 0penBmc sol set character-send-threshold 200
ipmitool -I lanplus -H 10.0.2.15 -U root -P 0penBmc sol set retry-count 5
ipmitool -I lanplus -H 10.0.2.15 -U root -P 0penBmc sol set retry-interval 20

3. Check Sol Conf, same as setting.
ipmitool -I lanplus -H 10.0.2.15 -U root -P 0penBmc sol info
Info: SOL parameter 'Nonvolatile Bitrate (5)' not supported
Info: SOL parameter 'Volatile Bitrate (6)' not supported
Set in progress                 : set-complete
Enabled                         : false
Force Encryption                : true
Force Authentication            : true
Privilege Level                 : USER
Character Accumulate Level (ms) : 1000
Character Send Threshold        : 200
Retry Count                     : 5
Retry Interval (ms)             : 200
Volatile Bit Rate (kbps)        : IPMI-Over-Serial-Setting
Non-Volatile Bit Rate (kbps)    : IPMI-Over-Serial-Setting
Payload Channel                 : 1 (0x01)
Payload Port                    : 623

Signed-off-by: Jian Zhang <zhangjian.3032@bytedance.com>
Change-Id: Iae79aa02a483e983c212d8cd617685fc33c64c67